{% set name = "libmpack-lua" %}
{% set version = "1.0.12" %}

package:
  name: {{ name }}
  version: {{ version }}

source:
  url: https://github.com/libmpack/{{ name }}/releases/download/{{ version }}/{{ name }}-{{ version }}.tar.gz
  sha256: 06b662b1f14cfaf592ecb3fab425bef20e51439509b7a1736a790ecc929ef8bf

build:
  number: 0
  skip: true  # [win]
  rpaths:
    - lib/lua/5.1/
    - lib/

requirements:
  build:
    - {{ compiler('c') }}
    - luarocks
    - luajit-openresty
  run:
    - luajit-openresty

test:
  commands:
    - luajit -e "require 'mpack'"

about:
  home: https://github.com/libmpack/libmpack-lua
  license: MIT
  license_family: MIT
  license_file: LICENSE-MIT
  summary: libmpack lua binding

extra:
  recipe-maintainers:
    - danielnachun
    - anjos
